# Generated by Django 2.0.2 on 2018-06-12 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientesAdministracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('cuantificador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pruebafoto2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientes', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categorias', models.CharField(choices=[('0', 'Arroces'), ('1', 'Vegetales'), ('2', 'Frutas'), ('3', 'Mariscos'), ('4', 'Parva'), ('5', 'Bebidas'), ('6', 'san valentin'), ('7', 'hallowen'), ('8', 'navidad')], max_length=100)),
                ('album', models.CharField(choices=[('0', 'veganos'), ('1', 'comidas rapidas'), ('2', 'tercera edad'), ('3', 'niños'), ('5', 'desayuno'), ('6', 'almuerzo'), ('7', 'cena')], max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('instrucciones', models.TextField()),
                ('preptimes', models.CharField(max_length=100)),
                ('coctime', models.CharField(max_length=100)),
                ('calorias', models.CharField(blank=True, max_length=100, null=True)),
                ('proteinas', models.CharField(blank=True, max_length=100, null=True)),
                ('carbohidratos', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='RecetasAdministracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categorias', models.CharField(choices=[('Arroces', 'Arroces'), ('vegetales', 'Vegetales'), ('Frutas', 'Frutas'), ('Mariscos', 'Mariscos'), ('Parva', 'Parva'), ('Bebidas', 'Bebidas'), ('san Valentin', 'san valentin'), ('hallowen', 'hallowen'), ('navidad', 'navidad')], max_length=100)),
                ('album', models.CharField(choices=[('veganos', 'veganos'), ('comidas rapidas', 'comidas rapidas'), ('tercera', 'tercera edad'), ('niños', 'niños'), ('desayuno', 'desayuno'), ('almuerzo', 'almuerzo'), ('cena', 'cena')], max_length=100)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('instrucciones', models.TextField()),
                ('coctime', models.CharField(max_length=100)),
                ('preptimes', models.CharField(max_length=100)),
                ('calorias', models.CharField(blank=True, max_length=100, null=True)),
                ('proteinas', models.CharField(blank=True, max_length=100, null=True)),
                ('carbohidratos', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredientesadministracion',
            name='recetas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredientesadministracion', to='subir.RecetasAdministracion'),
        ),
    ]
