# Generated by Django 2.0.2 on 2018-06-12 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetasadministracion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 12, 22, 39, 19, 318648)),
        ),
    ]
