# Generated by Django 2.0.2 on 2018-06-14 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir', '0003_auto_20180612_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetasadministracion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 6, 14, 0, 34, 34, 55773)),
        ),
    ]
