# Generated by Django 2.0.2 on 2020-01-27 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir', '0005_auto_20180614_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetasadministracion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 26, 20, 37, 20, 136305)),
        ),
    ]
