# Generated by Django 2.0.2 on 2024-02-06 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir', '0006_auto_20200126_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetasadministracion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 6, 13, 1, 27, 392510)),
        ),
    ]
